gazebo_ros_control:
  pid_gains:
    CHEST_JOINT0: {p: 80000,  d: 5, i: 0, i_clamp: 1}
    HEAD_JOINT0: {p: 5000,  d: 0.5, i: 0, i_clamp: 1}
    HEAD_JOINT1: {p: 5000,  d: 0.25, i: 0, i_clamp: 1}
    LARM_JOINT0: {p: 10000,  d: 5, i: 0, i_clamp: 1}
    LARM_JOINT1: {p: 60000,  d: 2, i: 0, i_clamp: 1}
    LARM_JOINT2: {p: 40000,  d: 0.5, i: 0, i_clamp: 1}
    LARM_JOINT3: {p: 1000,  d: 0.2, i: 0, i_clamp: 1}
    LARM_JOINT4: {p: 500,  d: 0.1, i: 0, i_clamp: 1}
    LARM_JOINT5: {p: 500,  d: 0.01, i: 0, i_clamp: 1}
    RARM_JOINT0: {p: 10000,  d: 5, i: 0, i_clamp: 1}
    RARM_JOINT1: {p: 60000,  d: 2, i: 0, i_clamp: 1}
    RARM_JOINT2: {p: 40000,  d: 0.5, i: 0, i_clamp: 1}
    RARM_JOINT3: {p: 1000,  d: 0.2, i: 0, i_clamp: 1}
    RARM_JOINT4: {p: 500,  d: 0.1, i: 0, i_clamp: 1}
    RARM_JOINT5: {p: 500,  d: 0.01, i: 0, i_clamp: 1}

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

streaming_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - CHEST_JOINT0
    - HEAD_JOINT0
    - HEAD_JOINT1
    - LARM_JOINT0
    - LARM_JOINT1
    - LARM_JOINT2
    - LARM_JOINT3
    - LARM_JOINT4
    - LARM_JOINT5
    - RARM_JOINT0
    - RARM_JOINT1
    - RARM_JOINT2
    - RARM_JOINT3
    - RARM_JOINT4
    - RARM_JOINT5
  RobotDescriptionParameter: /robot_description
  PositionSafetyFactor: 1.0
  VelocitySafetyFactor: 1.0
  AccelerationSafetyFactor: 0.3
  Kp: 200.0
  Kd: 10.0

larm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - LARM_JOINT0
    - LARM_JOINT1
    - LARM_JOINT2
    - LARM_JOINT3
    - LARM_JOINT4
    - LARM_JOINT5
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.1

  stop_trajectory_duration: 0.05
  state_publish_rate:  100
  action_monitor_rate: 10

rarm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - RARM_JOINT0
    - RARM_JOINT1
    - RARM_JOINT2
    - RARM_JOINT3
    - RARM_JOINT4
    - RARM_JOINT5
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.1

  stop_trajectory_duration: 0.05
  state_publish_rate:  100
  action_monitor_rate: 10

head_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - HEAD_JOINT0
    - HEAD_JOINT1
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.1

  stop_trajectory_duration: 0.05
  state_publish_rate:  100
  action_monitor_rate: 10

torso_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - CHEST_JOINT0
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.1

  stop_trajectory_duration: 0.05
  state_publish_rate:  100
  action_monitor_rate: 10

